version: '3.9'
services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: contacts_app
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app

  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: sh -c "composer install
              \&& php artisan key:generate
              \&& php artisan migrate
              \&& php artisan passport:install
              \&& php artisan serve --host=0.0.0.0"
    networks:
      - app

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - laravel
    env_file:
      - ./frontend/.env
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    command: sh -c "yarn install && yarn dev"
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  db-data:
